# Generated by Django 4.1.3 on 2022-12-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='area_home',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
